version: '3'

services:
  frontend:
    container_name: frontend
    build: ./
    platform: linux/x86_64
    ports:
      - 5173:5173
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    tty: true
    stdin_open: true